version: '3'
services:
        nginx:
                container_name: boiler-nginx
                image: nginx
                ports:
                        - 80:80
                volumes:
                        - ./nginx.conf:/etc/nginx/nginx.conf:ro 
                        - ../__sapper__/export:/usr/share/nginx/html:ro

 
