version: '3'
services:
  database:
    container_name: boiler_postgres
    env_file: .env.postgres
    image: postgres
    volumes:
      - "./postgresql:/var/lib/postgresql/data/pgdata:rw"
      - "./init.sql:/docker-entrypoint-initdb.d:ro"
      - "/etc/localtime:/etc/localtime:ro"
  git-gateway:
    build:
      context: https://github.com/netlify/git-gateway.git
      dockerfile: Dockerfile
    container_name: boiler_git-gateway
    env_file: .env.git-gateway
  gotrue:
    build:
      context: https://github.com/netlify/gotrue.git
      dockerfile: Dockerfile
    container_name: boiler_gotrue
    depends_on:
      - database
      - git-gateway
    env_file: .env.gotrue
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
  nginx:
    container_name: boiler_nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./__sapper__/export:/usr/share/nginx/html:ro"
